SPK_NAME = lftp
SPK_VERS = 4.8.3
SPK_REV = 1
SPK_ICON = src/lftp1.png
DSM_UI_DIR = app

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = VeryBueno
MAINTAINER_URL = https://github.com/VeryBueno
DESCRIPTION = "LFTP is a sophisticated file transfer program supporting a number of network protocols (ftp, http, sftp, fish, torrent)"
DISPLAY_NAME = LFTP
CHANGELOG = "Initial Release"

HOMEPAGE = https://lftp.yar.ru
LICENSE  = GPLv2/GPLv3

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

INSTALL_PREFIX = /usr/local/$(SPK_NAME)


include ../../mk/spksrc.spk.mk
